import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
	const router = useRouter();

	const handleClick = () => {
		console.log("Placing your order...");

		router.push("/product");
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>The Homepage</h1>

				<Link href="/blog">Blog</Link>

				<button onClick={handleClick}>Place Order</button>
			</main>
		</div>
	);
}
